import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "../globals.css";
import Grainient from "@/components/Grainient";
import Banner from "@/components/Banner/banner";
import Header from "@/components/Header/header";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import WithMe from "@/components/WithMe/withMe";
import Services from "@/components/Services/services";
import WorkModality from "@/components/WorkModality/workModality";
import ContactForm from "@/components/Form/form";
import Footer from "@/components/Footer/footer";
import { getDictionary, Locale } from "../i18n/dictionaries";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "es" }];
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const dict = await getDictionary(lang as Locale);

  return (
    <html lang={lang}>
      <body className={`${inter.variable} ${playfair.variable} antialiased`}>
        <Grainient
          color1="#c7cbe9"
          color2="#adafde"
          color3="#9099d6"
          timeSpeed={0.25}
          colorBalance={0}
          warpStrength={1}
          warpFrequency={5}
          warpSpeed={2}
          warpAmplitude={50}
          blendAngle={0}
          blendSoftness={0.05}
          rotationAmount={500}
          noiseScale={2}
          grainAmount={0.1}
          grainScale={2}
          grainAnimated={false}
          contrast={1.5}
          gamma={1}
          saturation={1}
          centerX={0}
          centerY={0}
          zoom={0.9}
        />
        <main className="relative z-10">
          <Header dict={dict} lang={lang} />
          <div className="max-w-[1280px] mx-auto w-[95%] sm:w-[90%] md:w-full">
            <Banner dict={dict} />
            <WithMe dict={dict} />
            <Services dict={dict} />
            <WorkModality dict={dict} />
            <ContactForm dict={dict} />
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
